#The amount of ticks before the trader will start spawning in a new world
traderSpawnDelay = 24000
#The amount of ticks before the trader will despawn
traderDespawnDelay = 24000
#The amount of ticks before the trader will replenish it's trades. Set to -1 to disable restocking
restockDelay = 48000
#The minimum level the trader can spawn
traderMinSpawnLevel = 0
#The maximum level the trader can spawn
traderMaxSpawnLevel = 256
#The amount of ticks to wait before trying to spawn a trader again if the spawn failed
spawnInterval = 12000
#Goblins will make a grunt noise while walking around. If you find it happening too often, you can increase the interval. Value is represented in ticks.
gruntNoiseInterval = 80
#If true, the goblin will try to hit back a player or mob that hit them
canAttackBack = true
#The chance out of one hundred that the trader will spawn on the Ender Dragon through vanilla re-summoning
spawnOnEnderDragonChance = 25
#The chance out of one hundred that the trader will spawn in the end
traderSpawnChance = 25

[trades]

	[trades.rare]
		#The maximum amount of trades that a golbin can have.
		manAmount = 4
		#The minimum amount of trades that a golbin will have.
		minAmount = 3
		#The chance this trade rarity will be included in the goblin's trades
		includeChance = 1.0

	[trades.uncommon]
		#The maximum amount of trades that a golbin can have.
		manAmount = 5
		#The minimum amount of trades that a golbin will have.
		minAmount = 3
		#The chance this trade rarity will be included in the goblin's trades
		includeChance = 1.0

	[trades.legendary]
		#The chance this trade rarity will be included in the goblin's trades
		includeChance = 0.1
		#The minimum amount of trades that a golbin will have.
		minAmount = 1
		#The maximum amount of trades that a golbin can have.
		manAmount = 1

	[trades.epic]
		#The minimum amount of trades that a golbin will have.
		minAmount = 0
		#The maximum amount of trades that a golbin can have.
		manAmount = 2
		#The chance this trade rarity will be included in the goblin's trades
		includeChance = 1.0

	[trades.common]
		#The chance this trade rarity will be included in the goblin's trades
		includeChance = 1.0
		#The minimum amount of trades that a golbin will have.
		minAmount = 5
		#The maximum amount of trades that a golbin can have.
		manAmount = 8

